# .coveralls.yml example configuration

repo_token: vg1xLDGuonevvOQxdsnUBKIvTRfghDKGH # should be kept secret!
service_name: travis-ci

coverage_clover: build/logs/clover.xml
json_path: build/logs/coveralls-upload.json
